version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '2023:2023'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network


volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
